# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yolostreamingoutput.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19yolostreamingoutput.proto\x12\x13yolostreamingoutput\"\x1e\n\x0bYoloRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\tYoloReply\x12\x11\n\tdetection\x18\x01 \x01(\t2e\n\x0cYoloStreamer\x12U\n\ryoloDetection\x12 .yolostreamingoutput.YoloRequest\x1a\x1e.yolostreamingoutput.YoloReply\"\x00\x30\x01\x42\x0f\n\x07\x65x.grpc\xa2\x02\x03HSWb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yolostreamingoutput_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\007ex.grpc\242\002\003HSW'
  _YOLOREQUEST._serialized_start=50
  _YOLOREQUEST._serialized_end=80
  _YOLOREPLY._serialized_start=82
  _YOLOREPLY._serialized_end=112
  _YOLOSTREAMER._serialized_start=114
  _YOLOSTREAMER._serialized_end=215
# @@protoc_insertion_point(module_scope)
