# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import yolostreamingoutput_pb2 as yolostreamingoutput__pb2


class YoloStreamerStub(object):
    """The YOLO streamer output definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.yoloDetection = channel.unary_stream(
                '/yolostreamingoutput.YoloStreamer/yoloDetection',
                request_serializer=yolostreamingoutput__pb2.YoloRequest.SerializeToString,
                response_deserializer=yolostreamingoutput__pb2.YoloReply.FromString,
                )


class YoloStreamerServicer(object):
    """The YOLO streamer output definition.
    """

    def yoloDetection(self, request, context):
        """Sends detected rectangles
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YoloStreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'yoloDetection': grpc.unary_stream_rpc_method_handler(
                    servicer.yoloDetection,
                    request_deserializer=yolostreamingoutput__pb2.YoloRequest.FromString,
                    response_serializer=yolostreamingoutput__pb2.YoloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yolostreamingoutput.YoloStreamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class YoloStreamer(object):
    """The YOLO streamer output definition.
    """

    @staticmethod
    def yoloDetection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/yolostreamingoutput.YoloStreamer/yoloDetection',
            yolostreamingoutput__pb2.YoloRequest.SerializeToString,
            yolostreamingoutput__pb2.YoloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
